language: python
virtualenv:
  system_site_packages: true
env:
  matrix:
    - PYTHON_VERSION="2.7" FROM="setup.py"
    - PYTHON_VERSION="3.5" FROM="setup.py"
    - PYTHON_VERSION="2.7" FROM="github"
    - PYTHON_VERSION="3.5" FROM="github"
    - PYTHON_VERSION="2.7" FROM="pypi"
    - PYTHON_VERSION="3.5" FROM="pypi"
install: source ./ci/.travis_install.sh
script: bash ./ci/.travis_test.sh
cache: apt
sudo: false
notifications:
  email:
    recipients:
      - mail@sebastianraschka.com
    on_success: always
    on_failure: always
